using System;
using System.Collections.Generic;

public enum JenisBarang
{
    SIX_MONOCRYSTALLINE_SOLAR_PANEL,
    THREE_MONOCRYSTALLINE_SOLAR_PANEL,
    STAND_MONOCRYSTALLINE_SOLAR_PANEL,
    SINGLE_MONOCRYSTALLINE_SOLAR_PANEL
}

public enum Harga_Barang
{
    SIX_MONOCRYSTALLINE_SOLAR_PANEL = 4800000,
    THREE_MONOCRYSTALLINE_SOLAR_PANEL = 2500000,
    STAND_MONOCRYSTALLINE_SOLAR_PANEL = 2350000 ,
    SINGLE_MONOCRYSTALLINE_SOLAR_PANEL = 1450000
}
